global:
  dashboards:
    - SQL Servers - Alerts.json
    - SQL Servers.json
    - Web Servers.json
    - Docker Dashboard.json
    - elasticsearch.json
  datasources:
    - collector_alwayson.json
    - collector_appointments_stats.json
    - collector_eventlog.json
    - collector_failed_jobs.json
    - collector_missing_backups.json
    - collector_mssql_top_resource_consumers_avg_cpu_time_ms.json
    - collector_mssql_top_resource_consumers_cpu_seconds_per_minute.json
    - collector_mssql_top_resource_consumers_executions_per_minute.json
    - collector_mssql_top_resource_consumers_total_cpu_time_ms.json
    - collector_network_connection.json
    - collector_pending_tasks.json
    - collector_perfmon_generic.json
    - collector_perfmon_sql_databases.json
    - collector_perfmon_sql.json
    - collector_perfmon_web.json
    - collector_replication_distribution_agents_synschronization_status.json
    - collector_replication_logreader_queue.json
    - collector_service_broker.json
    - collector_wait_stats.json
    - collector.json
    - nxlogiis.json
    - collector_perfmon_logicaldisk.json
    - collector_perfmon_network_interface.json
    - collector_services.json
  elastic_retention_in_days: 30


Motorola-Zramim:
  dashboards:
    - Replication.json
    - SQL Servers Always On.json
  datasources:
    - InfluxDB.json
  elastic_retention_in_days: 3

logicait:
  dashboards:
  datasources:
    - InfluxDB.json
  elastic_retention_in_days: 3

ACFUK:
  dashboards:
    - SQL Servers Always On.json
    - SQL Servers QFlow.json
    - ACF Web Servers.json
  datasources:
    - InfluxDB.json
  elastic_retention_in_days: 3

afcon:
  dashboards:    
  datasources:
    - InfluxDB.json
  elastic_retention_in_days: 30

  powercom:
  dashboards:    
    - SQL Servers Always On.json
  datasources:
    - InfluxDB.json
  elastic_retention_in_days: 30