global:
  dashboards:
    - SQL Servers - Alerts.json
    - SQL Servers.json
    - Web Servers.json

Motorola-Zramim:
  dashboards:
    - Replication.json
  slack:
    - https://hooks.slack.com/services/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