global:
  dashboards:
    - Servers.json
    - SQL Servers - Alerts.json
    - SQL Servers.json
    - Web Servers.json
    - Docker Dashboard.json
    - elasticsearch.json
  datasources:
    - collector_alwayson.json
    - collector_appointments_stats.json
    - collector_eventlog.json
    - collector_failed_jobs.json
    - collector_missing_backups.json
    - collector_mssql_top_resource_consumers_avg_cpu_time_ms.json
    - collector_mssql_top_resource_consumers_cpu_seconds_per_minute.json
    - collector_mssql_top_resource_consumers_executions_per_minute.json
    - collector_mssql_top_resource_consumers_total_cpu_time_ms.json
    - collector_network_connection.json
    - collector_pending_tasks.json
    - collector_perfmon.json
    - collector_replication_distribution_agents_synschronization_status.json
    - collector_replication_logreader_queue.json
    - collector_service_broker.json
    - collector_wait_stats.json
    - collector.json
    - nxlogiis.json
    - collector_services.json
    - collector_fastpark_blacklist.json
    - collector_fastpark_occupancy.json
    - collector_fastpark_entries_exits.json
  elastic_retention_in_days: 30


Motorola-Zramim:
  dashboards:
    - Replication.json
    - SQL Servers Always On.json
  datasources:
    - InfluxDB.json
  elastic_retention_in_days: 3

logicait:
  dashboards:
  datasources:
    - InfluxDB.json
  elastic_retention_in_days: 3

acfuk:
  dashboards:
    - SQL Servers Always On.json
    - SQL Servers QFlow.json
    - ACF Web Servers.json
  datasources:
    - InfluxDB.json
    - collector_qflow_eventlog.json
  elastic_retention_in_days: 3

afcon:
  dashboards:    
    - Replication.json
    - Afcon.json
  datasources:
    - InfluxDB.json
    - collector_fastpark_blacklist.json
    - collector_fastpark_occupancy.json
    - collector_fastpark_entries_exits.json
  elastic_retention_in_days: 30

powercom:
  dashboards:    
    - SQL Servers Always On.json
  datasources:
    - InfluxDB.json
  elastic_retention_in_days: 30

herzeliya:
  dashboards:    
    - Replication.json
    - Afcon.json
  datasources:
    - InfluxDB.json
  elastic_retention_in_days: 30

idemitsu:
  dashboards:    
  datasources:
    - InfluxDB.json
  elastic_retention_in_days: 30

reshut:
  dashboards:   
    - SQL Servers Always On.json 
  datasources:
    - InfluxDB.json
  elastic_retention_in_days: 30
