{
 "title": "ACF Web Servers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Client",
    "query": "{\"find\":\"terms\",\"field\": \"@server.keyword\"}"
   },
   { "name": "Environment", "query": "PROD, PRD, PD, PERF, PE" },
   {
    "name": "Servers",
    "query": "{\"find\":\"terms\",\"field\": \"@server.keyword\", \"query\": \"@server.keyword:*$Client* AND @server.keyword:*$Environment*\"}"
   }
  ]
 },
 "panels": [
  { "title": "IIS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IIS - requests count - 1000ms",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timeofevent", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status.keyword: 200 AND timetaken: [0 TO 1000] AND hostname.keyword:$Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IIS - requests count - 2000ms",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timeofevent", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status.keyword: 200 AND timetaken: [1001 TO 2000] AND hostname.keyword:$Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IIS - requests count - 3000ms",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timeofevent", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status.keyword: 200 AND timetaken: [2001 TO 3000] AND hostname.keyword:$Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IIS - requests count - > 3000ms",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timeofevent", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status.keyword: 200 AND timetaken: [3001 TO *] AND hostname.keyword:$Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IIS - success requests by server ",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timeofevent", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status.keyword: 200 AND hostname.keyword:$Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IIS - failed requests by server",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "hostname.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timeofevent", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT status.keyword: 200 AND hostname.keyword:$Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IIS success requests by url",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "page.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timeofevent", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status.keyword: 200 AND hostname.keyword:$Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IIS - success requests by url",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "page.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timeofevent", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "status.keyword: 200 AND hostname.keyword:$Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IIS failed requests by url",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "page.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timeofevent", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT status.keyword: 200 AND hostname.keyword:$Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IIS - failed requests by url",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "status.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "page.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timeofevent", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT status.keyword: 200 AND hostname.keyword:$Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Web Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "requests current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "asp.net v4.0.30319\\requests current",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "@server.keyword: $Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "current connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "web service(_total)\\current connections",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "@server.keyword: $Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "request execution time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "asp.net v4.0.30319\\request execution time",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "@server.keyword: $Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": ".net clr exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "#net clr exceptions(_global_)\\# of exceps thrown",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "@server.keyword: $Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "requests wait time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "asp.net v4.0.30319\\request wait time",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "@server.keyword: $Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "requests disconnected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "asp.net v4.0.30319\\requests disconnected",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "@server.keyword: $Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "errors total/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "asp.net applications(__total__)\\errors total/sec",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "@server.keyword: $Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "errors unhandled during execution/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "asp.net applications(__total__)\\errors unhandled during execution/sec",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "@server.keyword: $Servers",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "% processor time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "processor(_total)\\% processor time",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "processor queue length",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "system\\processor queue length", "id": "1", "type": "avg" }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Adapter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet adapter bytes sent/sec | bytes received/sec ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "network interface(microsoft hyper-v network adapter)\\bytes sent/sec",
         "id": "1",
         "type": "avg"
        },
        {
         "field": "network interface(microsoft hyper-v network adapter)\\bytes received/sec",
         "id": "4",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Ethernet adapter bytes sent/sec ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "network interface(microsoft hyper-v network adapter)\\bytes sent/sec",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Ethernet adapter bytes received/sec ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "network interface(microsoft hyper-v network adapter)\\bytes received/sec",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "C:\\ - avg. disk sec/read  |  avg. disk sec/write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(c:)\\avg. disk sec/read",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(c:)\\avg. disk sec/write",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "D:\\ - avg. disk sec/read  |  avg. disk sec/write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(d:)\\avg. disk sec/read",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(d:)\\avg. disk sec/write",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "F:\\ - avg. disk sec/read  |  avg. disk sec/write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(f:)\\avg. disk sec/read",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(f:)\\avg. disk sec/write",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "C:\\ - disk read bytes/sec  |  disk write bytes/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(c:)\\disk read bytes/sec",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(c:)\\disk write bytes/sec",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "D:\\ - disk read bytes/sec  |  disk write bytes/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(d:)\\disk read bytes/sec",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(d:)\\disk write bytes/sec",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "F:\\ - disk read bytes/sec  |  disk write bytes/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(f:)\\disk read bytes/sec",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(f:)\\disk write bytes/sec",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "C:\\ - disk read/sec  |  disk write/sec",
     "type": "timeseries",
     "description": "Number of read and write operations per sec",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(c:)\\disk reads/sec",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(c:)\\disk writes/sec",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "D:\\ - disk read/sec  |  disk write/sec",
     "type": "timeseries",
     "description": "Number of read and write operations per sec",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(d:)\\disk reads/sec",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(d:)\\disk writes/sec",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "F:\\ - disk read/sec  |  disk write/sec",
     "type": "timeseries",
     "description": "Number of read and write operations per sec",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(f:)\\disk reads/sec",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "logicaldisk(f:)\\disk writes/sec",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "@server.keyword: $Servers",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}