{
 "title": "Afcon",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "service.keyword",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "Status.keyword",
       "id": "5",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT Status.keyword: Running AND NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "cars entries | exists",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "alias": "{{term @server.keyword}}: Entries",
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "Entry_Type.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cnt", "id": "1", "type": "avg" }
     ],
     "query": "Entry_Type.keyword : 1",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term @server.keyword}}: Exits",
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "Entry_Type.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cnt", "id": "1", "type": "avg" }
     ],
     "query": "Entry_Type.keyword : 2",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term @server.keyword}} {{term database.keyword}}: rows",
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "Entry_Type.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cnt", "id": "1", "type": "avg" }
     ],
     "query": "Entry_Type.keyword : 3",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "black list",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "Car_No",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "cars occupancy",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "cnt", "id": "1", "type": "max" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "time out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "type.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "timeofevent", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type.keyword: SiteServerService AND collector_message.keyword: *TimeOut*",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}