{
 "title": "Replication",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "servers",
    "query": "{\"find\":\"terms\",\"field\": \"@server.keyword\"}"
   },
   {
    "name": "publications",
    "query": "{\"find\":\"terms\",\"field\": \"publication.keyword\"}"
   },
   {
    "name": "queues",
    "query": "{\"find\":\"terms\",\"field\": \"queue_name.keyword\"}"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "log reader queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "database_name.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "replicated_transactions", "id": "1", "type": "max" }
       ],
       "query": "@server.keyword: $servers",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "distribution agents commands - $publications",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "repeat": "publications",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{term subscriber.keyword}}",
       "bucketAggs": [
        {
         "field": "subscriber.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "publication.keyword",
         "id": "4",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "command", "id": "1", "type": "avg" }
       ],
       "query": "publication.keyword: \"$publications\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "distribution agents status - $publications",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "repeat": "publications",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "{{term subscriber.keyword}}",
       "bucketAggs": [
        {
         "field": "subscriber.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "publication.keyword",
         "id": "4",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "status", "id": "1", "type": "max" }
       ],
       "query": "publication.keyword: \"$publications\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "distribution agents status ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "subscriber.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "publication.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "status", "id": "1", "type": "avg" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "distribution agents commands",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "subscriber.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "publication.keyword",
         "id": "4",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "command", "id": "1", "type": "avg" }
       ],
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "log reader queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "database_name.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "replicated_transactions", "id": "1", "type": "max" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}