{
 "title": "SQL Servers - Alerts",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Always On", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "always on log queue size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "alias": "{{term @server.keyword}}:  {{field}}",
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "log_send_queue_size", "id": "1", "type": "max" }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term @server.keyword}}:  {{field}}",
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "redo_queue_size", "id": "4", "type": "max" }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "always on latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "{{term @server.keyword}}: {{field}}",
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "secondary_lag_seconds", "id": "1", "type": "max" }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term @server.keyword}}: {{field}}",
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "last_commit_time_ss", "id": "1", "type": "max" }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{term @server.keyword}}: {{field}}",
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "last_redone_time_ss", "id": "1", "type": "max" }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "always on synchronization health",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{{term @server.keyword}}: synchronization_health",
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "synchronization_health_desc.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT (synchronization_health_desc.keyword: HEALTHY)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "always on synchronization state",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "{{term @server.keyword}}: synchronization_state",
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "synchronization_state_desc.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT (synchronization_state_desc.keyword: SYNCHRONIZED OR synchronization_state_desc.keyword: SYNCHRONIZING)",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Generic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "services",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "service.keyword",
       "id": "4",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "Status.keyword",
       "id": "5",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT Status.keyword: Running AND NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "memory grants pending",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sqlserver:memory manager\\memory grants pending",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "work queue count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "work_queue_count", "id": "1", "type": "avg" }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "service broker queues",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "repeat": "queues",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "6",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "queue_name.keyword",
       "id": "7",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "database.keyword",
       "id": "8",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "rows_count", "id": "1", "type": "avg" }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "number of deadlocks/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sqlserver:locks(_total)\\number of deadlocks/sec",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "user connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "4", "settings": { "interval": "1m", "min_doc_count": "1", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "sqlserver:general statistics\\user connections",
       "hide": false,
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "% processor time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": "1", "offset": "0", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "processor(_total)\\% processor time",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "processor queue length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "system\\processor queue length", "id": "1", "type": "avg" }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "C:\\ - logical disk % free disk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "drive_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "logicaldisk()\\% free space", "id": "1", "type": "avg" }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Collectors Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collectors status",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "@server.keyword",
         "id": "4",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        {
         "field": "collector_name.keyword",
         "id": "5",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_count", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Backups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "missing backups",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "database.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "type.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "Count", "id": "1", "type": "max" }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Event Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Application and System event log",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@log_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "Sevirity.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "Id.keyword",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "Message.keyword",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Application event log",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System event log",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "SQL Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "sql jobs",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@server.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "job_name.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "step_name.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "sql failed jobs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "query": "NOT (@server.keyword: /.*SQLPE.*/) AND NOT (@server.keyword: /.*ATLAS.*/) ",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}